### ISSUE TITLE
Maximize only works for chats, not Status

### ISSUE THREAD

**Issue by nirokun** [CleoMenezes/fullscreen-wpp#1]
Histories tab stays at the same size as usual.
![WhatsApp Image 2022-03-23 at 4 35 15 PM](https://user-images.githubusercontent.com/46892820/159781556-cb784cae-4ed7-4646-a757-c613a2a029de.jpeg)

**Comment by CleoMenezesJr** [comment]
Thanks for letting me know, as I never open it I use Story, so I've never tested it. I started fixing it later.
