### ISSUE TITLE
layout move to right edge..

### ISSUE THREAD

**Issue by biladina** [CleoMenezes/fullscreen-wpp#3]
hi, I'm starting have this issue like yesterday, the WA layout kind move entirely to the right edge.. I tried to enable/disable the extension and also uninstall/install the extension, no luck..

this is the layout right now..
![1](https://github.com/CleoMenezesJr/Maximize-WhatsApp-Web/assets/10651085/5259bfe6-118c-423f-9c7d-23f99c7db3e0)

this is the extension version that I use, which from the release date also look like yesterday..
![2](https://github.com/CleoMenezesJr/Maximize-WhatsApp-Web/assets/10651085/a92e4f70-4558-476b-9a6e-0ac3e5698917)

I'm using Firefox 115.9.1 ESR version..
![Screenshot_20240401_120002](https://github.com/CleoMenezesJr/Maximize-WhatsApp-Web/assets/10651085/9d7902aa-f96e-4723-800d-478e0f0debf6)

**Comment by CleoMenezesJr** [comment]
Please can you disable the extension, reload the page, open the firefox console and run:
```js
 document.evaluate(
    "/html/body/div[1]/div/div/div[2]",
    document,
    null,
    XPathResult.FIRST_ORDERED_NODE_TYPE,
    null,
  ).singleNodeValue;
```
Which element was selected?

**Comment by eeTurcanu** [comment]
Hello,

I had the same problem (Firefox 124.0.1 if relevant)

> Which element was selected?

`<div class="_2QgSC">`
Should I also attach a screenshot?

**Comment by CleoMenezesJr** [comment]
yes, please. Hovering the selected item.

**Comment by biladina** [comment]
> Please can you disable the extension, reload the page, open the firefox console and run:
> 
> ```js
>  document.evaluate(
>     "/html/body/div[1]/div/div/div[2]",
>     document,
>     null,
>     XPathResult.FIRST_ORDERED_NODE_TYPE,
>     null,
>   ).singleNodeValue;
> ```
> 
> Which element was selected?


![Screenshot_20240401_202758-1](https://github.com/CleoMenezesJr/Maximize-WhatsApp-Web/assets/10651085/d1c71e72-8c2d-4d1d-a91c-334382e1e94f)

**Comment by CleoMenezesJr** [comment]
Hmm. It's selecting the correct element, and I don't see what the problem could be. What is the size of your monitor? Other extensions?

**Comment by biladina** [comment]
> Hmm. It's selecting the correct element, and I don't see what the problem could be. What is the size of your monitor? Other extensions?

I'm using 15 inch IPS laptop monitor, 1920x1080

I already tried to disable all other extension, but no luck.. this is list of my extension..
https://addons.mozilla.org/en-US/firefox/addon/screenshot-capture-annotate
https://addons.mozilla.org/en-US/firefox/addon/facebook-container/
https://addons.mozilla.org/en-US/firefox/addon/location-guard/
https://addons.mozilla.org/en-US/firefox/addon/tab-session-manager/
https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/
https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher/


and I already using your extension since juny/july 2023 if I remembered correctly.. no problem ever since.. maybe something change at whatsapp..

**Comment by CleoMenezesJr** [comment]
Unfortunately, I can't reproduce the problem. Do you know CSS? If so, you can search for the head tag and a style that contains changes to the `#maximize-wpp` ID. You can play around a bit and see what could be causing this or what you can fix on your end.

**Comment by biladina** [comment]
> Unfortunately, I can't reproduce the problem. Do you know CSS? If so, you can search for the head tag and a style that contains changes to the `#maximize-wpp` ID. You can play around a bit and see what could be causing this or what you can fix on your end.

for CSS, a little bit (curse being backend developer 😅😅😅).. I will try to see what cause the problem and maybe can come up with something.. thanks for pointing out..

**Comment by CleoMenezesJr** [comment]
Feel free to mess it up and find some clue. Don't bother to ask.

**Comment by CleoMenezesJr** [comment]
Guys, just out of conscience. Try to do the following:
1. disable the extension
2. reload WhatsApp web
3. open the console and enter the following code:

```javascript
const checkExist = setInterval(() => {
  const bodyApp = document.querySelectorAll('#app > div > div:last-child')[0];

  const loadingPage = document.documentElement.classList.contains("wf-loading");

  if (bodyApp != null && loadingPage) {
    bodyApp.id = "maximize-wpp";
    clearInterval(checkExist);
  }
}, 100);

const style = document.createElement("style");
style.setAttribute("type", "text/css");
style.innerHTML = `
  /* Maximize WhatsApp Extension */
  #maximize-wpp {
      max-width: initial !important;
      width: 100% !important;
      height: 100% !important;
      margin: 0 !important;
      position: unset !important;
  }
`;
document.head.appendChild(style);
```

I just managed to reproduce your problem. In fact, I was selecting the wrong element. Unfortunately, I had to change the approach because WhatsApp is using different classes for some users/versions (I don't know) so searching for the element by class was no longer working. I tried to get it through XPath, but for some reason it works well for me, but not for you. Now I'm trying another approach, which is by referencing the app ID. It worked here. I hope it works out there.

**Comment by biladina** [comment]
> Guys, just out of conscience. Try to do the following:
> 
>     1. disable the extension
> 
>     2. reload WhatsApp web
> 
>     3. open the console and enter the following code:
> 
> 
> ```js
> const checkExist = setInterval(() => {
>   const bodyApp = document.querySelectorAll('#app > div > div:last-child')[0];
> 
>   const loadingPage = document.documentElement.classList.contains("wf-loading");
> 
>   if (bodyApp != null && loadingPage) {
>     bodyApp.id = "maximize-wpp";
>     clearInterval(checkExist);
>   }
> }, 100);
> 
> const style = document.createElement("style");
> style.setAttribute("type", "text/css");
> style.innerHTML = `
>   /* Maximize WhatsApp Extension */
>   #maximize-wpp {
>       max-width: initial !important;
>       width: 100% !important;
>       height: 100% !important;
>       margin: 0 !important;
>       position: unset !important;
>   }
> `;
> document.head.appendChild(style);
> ```
> 
> I just managed to reproduce your problem. In fact, I was selecting the wrong element. Unfortunately, I had to change the approach because WhatsApp is using different classes for some users/versions (I don't know) so searching for the element by class was no longer working. I tried to get it through XPath, but for some reason it works well for me, but not for you. Now I'm trying another approach, which is by referencing the app ID. It worked here. I hope it works out there.

I just test this, it works..
![Untitled](https://github.com/CleoMenezesJr/Maximize-WhatsApp-Web/assets/10651085/d1cd21e1-1752-46be-ba70-372725386cfc)
