### ISSUE TITLE
Add-ons disappear from Firefox Add Ons website

### ISSUE THREAD

**Issue by biladina** [CleoMenezes/fullscreen-wpp#4]
hi, is there something wrong with the add ons? I'm trying to install the add ons, but the page says `Oops! We can’t find that page`

![Screenshot_20241022_185317](https://github.com/user-attachments/assets/cd529d4c-a26c-4f86-9338-6a896a2a50a5)

**Comment by Ningusta** [comment]
For now, I'd recommend downloading the extension manually in Firefox, as shown after the image.
It works basically the same way, although you'll need to put the extension folder somewhere you won't accidentally delete it.

**Comment by CleoMenezesJr** [comment]
Sorry for the delay in responding. It turns out that Firefox removed the extension due to "trademark infringement" concerns. Maybe the problem is the name or the icon. I will make these changes and in a few days it will be available again.

**Comment by CleoMenezesJr** [comment]
Hey, guys. Just release v2.4.
The extension will be available again soon on https://addons.mozilla.org/en-US/firefox/addon/maximize-wpp-web/

I had to change the logo and put several warnings that it is not associated with WhatsApp. I hope it doesn't get removed again.
